---
- name: Capture network traffic and save as PCAP file on Control Node and copy to Manage Node
  hosts: ControlNode  # This targets the Control Node for traffic capture
  gather_facts: yes  
  vars:
    capture_path: "/home/zamora/CPE213/TIP_HOA-8.1_ZAMORA_Angelo"
    pcap_filename: "capture.pcap"  # Name of the PCAP file
    interface: "enp0s3"  # Network interface to capture on (e.g., eth0, wlan0, etc.)
    manage_node_ip: "192.168.56.11"  # IP address of the Manage Node

  tasks:
    - name: Ensure the capture directory exists on Control Node
      file:
        path: "{{ capture_path }}"
        state: directory
        owner: zamora
        group: zamora
        mode: '0755'
      tags: 
        - setup
        - directory_creation

    - name: Install tshark on Ubuntu (Control Node)
      apt:
        name: tshark
        state: present
      become: yes
      tags:
        - setup
        - tshark_install

    - name: Start Tshark capture to create a PCAP file on Control Node
      command: >
        sudo tshark -i {{ interface }} -f "tcp port 80" -a duration:60 -c 10 -s 96 -n -b filesize:1024 -w {{ capture_path }}/{{ pcap_filename }} 
      become: yes
      become_user: zamora  
      tags:
        - capture
        - tshark_capture

    - name: Wait for the capture to complete
      pause:
        seconds: 10
      tags:
        - capture
        - pause_after_capture

    - name: Verify the capture file exists on Control Node
      stat:
        path: "{{ capture_path }}/{{ pcap_filename }}"
      register: pcap_file_stat
      tags:
        - capture
        - verify_capture

    - name: Debug output to confirm the file existence on Control Node
      debug:
        msg: "PCAP file exists at: {{ capture_path }}/{{ pcap_filename }} - {{ pcap_file_stat.stat.exists }}"
      tags:
        - capture
        - debug_capture_file

    - name: Copy PCAP file from Control Node to Manage Node
      copy:
        src: "{{ capture_path }}/{{ pcap_filename }}"
        dest: "/home/zamora/{{ pcap_filename }}"
        owner: zamora
        group: zamora
        mode: '0644'
      delegate_to: "{{ manage_node_ip }}"  # This directs the copy to the Manage Node
      tags:
        - copy
        - pcap_copy
