---
- name: Collect system logs from Control Node to Manage Node using journalctl
  hosts: all
  become: true 
  tasks:
    - name: Ensure the logs directory exists on Manage Node
      ansible.builtin.file:
        path: "/home/zamora/logs"
        state: directory
        mode: '0755'

    - name: Collect system logs from the last day using journalctl 
      ansible.builtin.shell:
        cmd: "journalctl --since '1 day ago' > /home/zamora/journal_logs.txt"
      delegate_to: localhost

    - name: Fetch journal logs file to Manage Node
      ansible.builtin.fetch:
        src: "/home/zamora/journal_logs.txt"
        dest: "/home/zamora/logs/"
        flat: yes
      delegate_to: ManageNode
